name: refresh-tokens
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://tanager.app/api/twitter/token' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}'
